
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xetflix
      MYSQL_USER: user
      MYSQL_PASSWORD: 313969
    volumes:
      - db_data:/var/lib/mysql
      - ./db/xetflixdb.sql:/docker-entrypoint-initdb.d/xetflixdb.sql

volumes:
  db_data: